# API de gestion d'utilisateur

openapi: 3.0.3
info:
  title: My openAPI exo2
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /users:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: size
          schema:
            type: integer
          required: true
      responses:
        200:
          description: list founded
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                  example:
                    id: 1
                    name: Alice
                    email: alice@example.com
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                example:
                  error: "Bad types for provided query parameters"