# API de gestion d'utilisateur

openapi: 3.0.3
info:
  title: My openAPI exo2
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /users:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: size
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
      responses:
        200:
          description: list founded
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
        400:
          description: bad request
          content:
            text/plain:
              schema:
                type: string
                example: Bad types for provided query parameters