# API de gestion de taches

openapi: 3.0.3
info:
  title: My openAPI exo3
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /tasks:
    get:
      responses:
        200:
          description: get a list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Task"
      responses:
        201:
          description: List of news tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      responses:
        200:
          description: task deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
  /tasks/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      responses:
        200:
          description: task found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        404:
          description: task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                example:
                  error: "Task not found"
    delete:
      parameters:
        - name: taskId
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      responses:
        200:
          description: task deleted
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Task"

components:
  schemas:
    TaskId:
      type: integer
      example: 22

    TaskTitle:
      type: string
      example: 'go to grocery'

    IsCompleted:
      type: boolean
      example: true

    Task:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/TaskId"
        title:
          $ref: "#/components/schemas/TaskTitle"
        completed:
          $ref: "#/components/schemas/IsCompleted"