openapi: 3.0.3
info:
  title: My openAPI exo4
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /products:
    get:
      parameters:
        - $ref: "#/components/parameters/limitParam"
        - $ref: "#/components/parameters/qParam"
      responses:
        200:
          description: list of product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                withValues:
                  value:
                    - name: "chair"
                      expiration_datetime: "2025-12-31T23:59:59Z"
                      price: 55.99
                emptyList:
                  value: []

components:
  parameters:
    limitParam:
      description: maximum number of elements
      name: limit
      in: query
      schema:
        type: integer
      required: false

    qParam:
      description: search term
      name: q
      in: query
      schema:
        type: string
      required: false

  schemas:
    ProductName:
      type: string

    ProductExpiration_datetime:
      type: string
      format: date-time

    ProductPrice:
      type: number
      format: float

    Product:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/ProductName"
        expiration_datetime:
          $ref: "#/components/schemas/ProductExpiration_datetime"
        price:
          $ref: "#/components/schemas/ProductPrice"
